version: '3.4'
services:
  modem:
    build:
      context: ./
    restart: always
    image: modem-man
    container_name: modem-man
    hostname: modem-man
    ports:
      - "4001:4001"
    volumes:
	  - /d/projeler/my/modemManagement/logs/:/logs/
      - /d/projeler/my/modemManagement/data/:/data/