version: '3.4'
services:
  modem:
    build:
      context: ./
    restart: always
    image: homeutils
    container_name: homeutils
    hostname: homeutils
    ports:
      - "4001:4001"
    volumes:
      - /d/projeler/my/homeutils/logs/:/logs/
      - /d/projeler/my/homeutils/data/:/data/